spring.application.name=jobtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081

# show useful error details while debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Write logs to a file so we can always see the exception
logging.file.name=jobtracker.log
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
