spring.application.name=jobtracker

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d70liqlm5p6s73avje9g-a:5432/jobtracker_axh6
spring.datasource.username=jobtracker_axh6_user
spring.datasource.password=JLNcyyb9xiFQpJPN5lyxJlLwWsos0AKD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html


# show useful error details while debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Write logs to a file so we can always see the exception
logging.file.name=jobtracker.log
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
